### PR TITLE
Bump holochain to version 0.1.0

### PR DESCRIPTION
**Pull request by jdeepee**
Currently blocked by a websocket error on my machine, checking here to see if it will exist in CI also.

### CODE REVIEW

**Comment by jdeepee** [comment]
@fayeed could you also try the tests in this branch on Linux & Windows and let me know if you also have issues with the holochain admin websocket connection

**Comment by fayeed** [comment]
I updated holochain to 0.0.173 and cli to 0.0.68 tests are running but with errors while installing the DNA, I guess languages are incompatible with it. I had an error while building the binaries on Nix so used only cargo for both windows & linux.

This is the error:
```
{
  type: 'error',
  data: {
    type: 'internal_error',
    data: 'Conductor returned an error while using a ConductorApi: EntryDefStoreError(DnaError(WasmRuntimeError(RuntimeError { source: User(WasmError { file: "/home/fayeed/.cargo/registry/src/github.com-1ecc6299db9ec823/holochain_wasmer_host-0.0.82/src/guest.rs", line: 128, error: Serialize(Deserialize("wrong msgpack marker FixPos(0)")) }), wasm_trace: [], native_trace:    0: <unknown>\n' +
      '   1: <unknown>\n' +
      '   2: <unknown>\n' +
      '   3: <unknown>\n' +
      '   4: <unknown>\n' +
      '   5: <unknown>\n' +
      '   6: <unknown>\n' +
      '   7: <unknown>\n' +
      '   8: <unknown>\n' +
      '   9: <unknown>\n' +
      '  10: <unknown>\n' +
      ' })))'
  }
}
```

**Comment by jdeepee** [comment]
Cool thanks Fayeed, I think you are right and the languages need to be updated. I will get working on this shortly.

**Comment by jdeepee** [comment]
Update from this on my side: just ran the tests again... exact same code only difference is a different wifi network... and they passed. So thinking this whole websocket issue might be somehow related to: https://github.com/holochain/holochain/issues/1580

**Comment by jdeepee** [comment]
@lucksus  This is ready for merge and release, after review & adding windows, linux & signed mac holochain binaries to the deps release

**Review by lucksus — DISMISSED** [review]
macOS binaries are signed. Does the error in the failing CI test indicate that the Windows version of Holochain does not have the `lair_server_in_proc` option?

**Comment by jdeepee** [comment]
> macOS binaries are signed. Does the error in the failing CI test indicate that the Windows version of Holochain does not have the `lair_server_in_proc` option?

This was happening since windows tests were still using verson 0.0.161, this has just now been fixed

**Review by lucksus — APPROVED** [review]

**Pull request merged**
